In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

# Install TensorFlow

import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train,y_train), (x_test,y_test) = mnist.load_data()

x_train, x_test = x_train/255.0, x_test/255.0

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.5613541 , -0.30075127, -0.7049444 , -0.2254739 , -0.49709752,
        -0.07522814,  0.52725816,  0.3060489 , -0.5347663 , -0.27523088]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.06682452, 0.08671899, 0.05788625, 0.09349896, 0.07125939,
        0.10865699, 0.1984788 , 0.15909047, 0.06862506, 0.08896057]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.2195592

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 6s 94us/sample - loss: 0.2972 - accuracy: 0.9142
Epoch 2/5
60000/60000 [==============================] - 4s 63us/sample - loss: 0.1442 - accuracy: 0.9577
Epoch 3/5
60000/60000 [==============================] - 4s 68us/sample - loss: 0.1076 - accuracy: 0.9679
Epoch 4/5
60000/60000 [==============================] - 4s 67us/sample - loss: 0.0876 - accuracy: 0.9735
Epoch 5/5
60000/60000 [==============================] - 5s 76us/sample - loss: 0.0750 - accuracy: 0.9762


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 0s - loss: 0.0718 - accuracy: 0.9778


[0.0717763708845945, 0.9778]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: id=68347, shape=(5, 10), dtype=float32, numpy=
array([[4.2643084e-08, 1.0027607e-08, 5.6076756e-06, 2.3340296e-04,
        3.0001010e-10, 1.9862496e-07, 4.4789896e-13, 9.9975890e-01,
        2.3347607e-07, 1.5693846e-06],
       [6.7228973e-09, 4.2729469e-05, 9.9989557e-01, 1.5982886e-06,
        1.8468061e-14, 5.8234345e-05, 1.1359581e-07, 5.7607120e-11,
        1.6729996e-06, 7.2186368e-11],
       [5.9431347e-08, 9.9922299e-01, 2.6216279e-04, 1.1002144e-05,
        4.0714922e-06, 5.5775981e-06, 1.1934459e-05, 2.9824057e-04,
        1.8391266e-04, 1.2384005e-07],
       [9.9984860e-01, 7.9837505e-09, 1.6225342e-05, 2.0861258e-08,
        9.2275432e-06, 1.7188411e-05, 8.2077298e-05, 6.1876453e-06,
        6.1402531e-08, 2.0351974e-05],
       [3.3158726e-06, 9.7064738e-09, 9.2691707e-06, 1.5524066e-07,
        9.9854869e-01, 1.9540994e-06, 4.5778729e-06, 1.1616764e-04,
        1.2569182e-05, 1.3033649e-03]], dtype=float32)>